# Generated by Django 4.2.3 on 2023-07-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_conta_banco_alter_conta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('BS', 'Banco Santander'), ('BB', 'Banco do Brasil'), ('CE', 'Caixa economica')], max_length=2),
        ),
    ]
